[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#4CAF50"  # Green theme for "electric"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"